basic.forever(function () {
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.showString("G")
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P0, 0)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.showString("Y")
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P1, 0)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showString("R")
    basic.pause(500)
    pins.digitalWritePin(DigitalPin.P2, 0)
})
